# Generated by Django 4.1.4 on 2023-01-09 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coolshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
